# Generated by Django 5.2.4 on 2025-07-28 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categorylimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorylimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorylimit',
            name='period_type',
            field=models.CharField(choices=[('day', 'День'), ('month', 'Месяц'), ('year', 'Год')], default='month', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='categorylimit',
            unique_together={('user', 'category', 'period_type')},
        ),
    ]
